### Dia 18: "Mil anos no mar, mil anos nas montanhas" (Leky, 2017, p.299. O dia em que Selma sonhou com um Ocapi). 

##### Tweet 18.1 O que fazer com tanta informação? 
###### Falamos um bocado de diferentes bases dados, tem informação de pra tudo e de todos os jeitos. MAs vocês ja se perguntaram o que fazer com tanta informação ? 

###### entrar com GIF

##### Tweet 18.2 Bancos de dados estão a nossa disposição para que conhecimento.....

###### Mas agora que ja sabemos onde adquirir dados
###### entrar com GIF


##### Tweet 18.3 As possibilidades são inúmeras, umas vezes que você tem disposição tanta informação basta saber usar um SIg etc e tal.....


##### Tweet 18.4 Os Modelos de Nicho ecológicos (MNEs)  e Modelos de distribuição de espécies (MDSs)
###### As informações de occorências junto as ambientais ...e os algoritmos. Esse abordagem surgiu no ano tal e vem crescendo desde então


##### Tweet 18.5 Diferentes estudos (entendendo o passado e predições futuras)


### Tweete 18.6 Mostrar um estudo da science


### Tweete 18.7 Mostrar um estudo da Ecography

